### ISSUE TITLE
Release notes for version 2.0.0

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf-website#104]
As sandbox is released, we are now have to announce it on our website to. Major stuff:

new components:
* sonata integration
* resource/resource-bundle/resource-rest-bundle with a puli "alike" resource handling

refactoring:
* treebrowser with fancy-tree going on resource system
* all sonata out into sonata integration
* improvements on sonata to get closer to orm version
* Symfony 3.3 compatebility
* PHP >= 5.6
* Directory Structure

....

future road to 2.1:
* discussion: https://github.com/symfony-cmf/symfony-cmf/issues/247
* discussion: https://github.com/symfony-cmf/symfony-cmf/issues/248

**Comment by dbu** [comment]
thanks for this collection. yeah, i will write up something based on this.
