### ISSUE TITLE
php version on server

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf-website#66]
the server still runs an old php. running composer install no longer works, as FOSRestBundle requires at least PHP 5.3.9 ...

any chance to update that server?

**Comment by lsmith77** [comment]
let me see if I can get us a dedicated setup some where else as the issue with the PHP version is that several other OSS projects run on the same server.

**Comment by lsmith77** [comment]
@dbu and I will have a conf call with platform.sh on thursday afternoon

**Comment by lsmith77** [comment]
we will get a free platform.sh instance to which we will be able to automatically deploy via a webhook. I will clean up the about section while I am at it and replace ServerGrove with Platform.sh. hope that is cool with everyone.

**Comment by WouterJ** [comment]
:+1: (btw, I'm also thinking about redesigning the website)

**Comment by lsmith77** [comment]
ok .. I have access to the repo on platform.sh .. I think I should be able to get the site running on there this week.

**Comment by lsmith77** [comment]
see #70

**Comment by lsmith77** [comment]
just waiting on the DNS to be updated

**Comment by lsmith77** [comment]
all done ..

BTW any branch and PR will build automatically on platform.sh
